{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Total Events Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pleiades_recv_events_total" }
   ]
  },
  {
   "title": "Total Events Published to Kafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pleiades_kafka_publish_events_total"
    }
   ]
  },
  {
   "title": "SSE Events Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pleiades_recv_events_total[1m])",
     "legendFormat": "events / s"
    }
   ]
  },
  {
   "title": "Event Lines Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pleiades_recv_event_lines_total[1m])",
     "legendFormat": "lines / s"
    }
   ]
  },
  {
   "title": "Kafka Publish Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pleiades_kafka_publish_events_total[1m])",
     "legendFormat": "publishes / s"
    }
   ]
  },
  {
   "title": "Kafka Write Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pleiades_kafka_publish_write_time_seconds",
     "legendFormat": "{{agg}}"
    }
   ]
  },
  {
   "title": "Kafka Writer Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pleiades_kafka_writer_errors_total[1m])",
     "legendFormat": "errors / s"
    }
   ]
  },
  {
   "title": "Goroutine Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pleiades_goroutine_restarts", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pleiades_recv_errors_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}