{
 "title": "Pleiades Aggregator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Event Consume Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate (pleiades_aggregator_event_count_total{service=\"pleiades-aggregate\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Consumer Offset Increase Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (rate(kafka_consumergroup_current_offset{consumergroup=\"pleiades-aggregator-group\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"pleiades-aggregator-group\"}",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Consumed Event Age at Aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_aggregator_message_lag_milliseconds_bucket[5m])) by (le))\n",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_aggregator_message_lag_milliseconds_bucket[5m])) by (le))\n",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Event Processing Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_aggregator_kafka_process_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_aggregator_kafka_process_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Aggregator Pod Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{service=\"pleiades-aggregate\"})",
     "legendFormat": "Pod Count"
    }
   ]
  },
  {
   "title": "Memory Allocation Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_memstats_alloc_bytes{service=\"pleiades-aggregate\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}