{
 "title": "Pleiades Ingest",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "SSE Event Receive Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pleiades_recv_events_total[5m]))",
     "legendFormat": "events / s - {{instance}}"
    }
   ]
  },
  {
   "title": "SSE Event Line Parse Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(rate(pleiades_recv_event_lines_total[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Events Published to Kafka [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(pleiades_kafka_publish_events_total[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSE Event Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pleiades_kafka_publish_lag_milliseconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Current Offset Increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (rate(kafka_topic_partition_current_offset{topic=\"pleiades-events\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Pleiades Ingest Goroutine Restarts [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (component)(rate(pleiades_goroutine_restarts{service=\"pleiades-ingest\"}[5m]))\n",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Kafka Writer Error Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(pleiades_kafka_writer_errors_total[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pleiades Ingest Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"pleiades-ingest\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}