{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Partitions under min-ISR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (kafka_cluster_partition_underminisr{topic=\"pleiades-events\"})",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Under-Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (kafka_topic_partition_under_replicated_partition{topic=\"pleiades-events\"})",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Partition Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (kafka_topic_partition_in_sync_replica{topic=\"pleiades-events\"})",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  }
 ]
}