{
 "title": "Pleiades Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingest: Event Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pleiades_recv_events_total[5m]))",
     "legendFormat": "event / s - {{instance}}"
    }
   ]
  },
  {
   "title": "Ingest: Publish Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(pleiades_kafka_publish_events_total[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Aggregate: Event Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate (pleiades_aggregator_event_count_total{service=\"pleiades-aggregate\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ingest: Event Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pleiades_kafka_publish_lag_milliseconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka: Topic Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (kafka_consumergroup_lag{consumergroup=\"pleiades-aggregator-group\"})",
     "legendFormat": "Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Aggregate: Event Age at Aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_aggregator_message_lag_milliseconds_bucket[5m])) by (le))\n",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_aggregator_message_lag_milliseconds_bucket[5m])) by (le))\n",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Web: Response Errors [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum by(path) (rate(pleiades_web_http_response_total{service=\"pleiades-web\", status=~\"[23]..\"}[5m]))\n/\nsum by(path) (rate(pleiades_web_http_response_total{service=\"pleiades-web\", status!~\"4..\"}[5m])))",
     "legendFormat": "Path: {{path}}"
    }
   ]
  },
  {
   "title": "Web: HTTP Response Latency [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_web_http_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_web_http_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Ingress Error Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-(sum by(path) (rate(nginx_ingress_controller_requests{service=\"pleiades-web\", status=~\"[23]..\"}[5m]))\n/\nsum by(path) (rate(nginx_ingress_controller_requests{service=\"pleiades-web\", status!~\"4..\"}[5m])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingest Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"pleiades-ingest\"})",
     "legendFormat": "Ingest"
    }
   ]
  },
  {
   "title": "Aggregate Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"pleiades-aggregate\"})",
     "legendFormat": "Ingest"
    }
   ]
  },
  {
   "title": "Web Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"pleiades-web\"})",
     "legendFormat": "Ingest"
    }
   ]
  }
 ]
}