{
 "title": "Web",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, status) (rate(pleiades_web_http_response_total{status!~\"4..\"}[5m]))",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Web Pod Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{service=\"pleiades-web\"})"
    }
   ]
  },
  {
   "title": "HTTP Response Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum by(path) (rate(pleiades_web_http_response_total{service=\"pleiades-web\", status=~\"[23]..\"}[5m]))\n/\nsum by(path) (rate(pleiades_web_http_response_total{service=\"pleiades-web\", status!~\"4..\"}[5m])))",
     "legendFormat": "Path: {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Response Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_web_http_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_web_http_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "JSON Marshalling Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pleiades_web_counter_marshal_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pleiades_web_counter_marshal_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  }
 ]
}